### ISSUE TITLE
"ADD TO QUEUE" & "ADD TO PLAYLIST"

### ISSUE THREAD

**Issue by bilalinamdar** [NabokD/pockettube#1]
Best Plugin but can you add the system fo "ADD TO QUEUE" & "ADD TO PLAYLIST" . As i only get the option to Watch later on videos under the pockettube subscription group on frontpage.
As it will be perfect match!

**Comment by NabokD** [comment]
Thank you! Yes, I'll add it in the next versions.

**Comment by NabokD** [comment]
It is available in a new version: https://www.youtube.com/watch?v=qCkOZ6NTrcc
You can add to queue and next add to playlist
