### ISSUE TITLE
[feature request] add a filter for 'streamed' vids.

### ISSUE THREAD

**Issue by mavalanche** [NabokD/pockettube#100]
Add in a filter for "streamed x hours ago" videos.
We currently have filters for 'uploads, live, scheduled, watched, #shorts'.
I would love to filter out recordings of streamed content, I don't have 5 hours to watch a stream after the fact, so don't need to see them in my sub feed :)

**Comment by NabokD** [comment]
Thank you for sharing!

**Comment by NabokD** [comment]
It's available in version 16.1.6 on Chrome
The filter 'Live' was extended, and now the current and past streams are filtered out. The only restriction is YouTube should be in the English language.
