### ISSUE TITLE
New video marks disappear 

### ISSUE THREAD

**Issue by SomeDude77** [NabokD/pockettube#102]
After the update yesterday the marks for new videos appear for 1-2 seconds when you open YT and then they all disappear. Reading your reddit page I see others have had the same problem. Happens in Firefox latest version.

**Comment by NabokD** [comment]
It's weird, still working for me. Do you have new upload indicators on the default YouTube subscription block? We collect from the default block.

**Comment by SomeDude77** [comment]
Yes, if I disable the extension the upload indicators on the default YT subs show up.

**Comment by SlyCooperReloadCoded** [comment]
I have the same issue, but worse. The new video marks only appear on YouTube's subscription list, but not on ones I create through the extension. I use it to alphabetically sort my subscriptions then use uBlock Origin to block the element that displays YouTube's own subscription list. This has worked fine for years, but as of a few days ago the blue marks no longer appear.

**Comment by NabokD** [comment]
Great news! I've reproduced the behavior and found the reason on Firefox. The new version is on review on the Firefox store and will be available in several days. I'll let you know!

**Comment by NabokD** [comment]
Unfortunately, Firefox has not reviewed my extension during the week, they are so slow in the summertime. I hope it'll be available in the first part of next week

**Comment by NabokD** [comment]
The new version 16.1.7, try to use it

**Comment by SlyCooperReloadCoded** [comment]
It doesn't want to work on my laptop, probably because it doesn't detect an update yet, but it does work on my desktop computer now.

**Comment by NabokD** [comment]
You can use the article to check version and update to latest one https://support.mozilla.org/en-US/kb/how-update-add-ons#w_updating-add-ons
