### ISSUE TITLE
Not playing all video's

### ISSUE THREAD

**Issue by RomeoSierra236** [NabokD/pockettube#103]
Normally when i open a group and click the first video, it creates an unlisted playlist with the first 50 video's. But recently when i do so it only works maybe 10%-20% of the time.  and just goes straight to the video i clicked the rest of the time

**Comment by NabokD** [comment]
What extension version are you using? The unlisted playlist is not working properly on YouTube itself, so we create a private when the unlisted fails to create. You should be logging on to YouTube to create a private playlist.

**Comment by RomeoSierra236** [comment]
16.1.5 and i am logged in

**Comment by NabokD** [comment]
Try to disable other extensions, maybe you have a conflict. I can't reproduce it, it's working fine for me.

**Comment by RomeoSierra236** [comment]
i dont know if you did anything to fix it but it works now 

Thank you
