### ISSUE TITLE
When I go to a channel and the click on "Videos", most of the videos are either invisible or the thumbnails flicker

### ISSUE THREAD

**Issue by iocapps** [NabokD/pockettube#105]
I have verified that this is caused by this particular extension.
Browser: edge
Version: latest (I have had this issue for many months)

I have tried reinstalling the extension from both chrome store and edge store. Nothing has helped.

**Comment by NabokD** [comment]
Hi, It's not a bug, I suspect you enabled content filters on a channel page, please check
![CleanShot 2024-06-29 at 13 16 39@2x](https://github.com/NabokD/pockettube/assets/10400731/1e658b26-13d7-43c6-b43a-a3c603c8dacb)

**Comment by iocapps** [comment]
@NabokD So when only "watched" is selected the video list reloads every second with a loading spinner showing up. That seems to be the bug.

But yeah, with that deselected I don't have issues.

**Comment by NabokD** [comment]
It's expected behavior, we try to find watched videos, if you don't have watched videos on first screen, it'll try to find when the list will be finished.
