### ISSUE TITLE
Grid view is broken: items per row no longer fit properly

### ISSUE THREAD

**Issue by andymerskin** [NabokD/pockettube#110]
Hey there, wanted to report an issue I started seeing today. I'm assuming YouTube came out with an update to their grid view spacing or some other CSS interfering with PocketTube's grid, causing the items per row to no longer fit properly. I'm not entirely sure if items aren't being shown (that should be), or whether items are breaking underneath to the next row (more likely).

1 less item is shown per row, no matter the selection. This applies at all window sizes and zoom levels I've tested.

**Browser:** Firefox 128.0.2, Windows 10 22H2
**Current behavior:** **4 items per row is selected**, with only 3 items showing per row:

![image](https://github.com/user-attachments/assets/146b6d91-2bdd-4b3d-a0d3-75b20701268e)

**Comment by HidyHo** [comment]
I also have the same issue on Chrome Version 126.0.6478.178 (Official Build) (64-bit) on ChromeOS Version 126.0.6478.214 (Official Build) (64-bit).  The issue started about a day ago.

**Comment by NabokD** [comment]
Thank you for letting me know, yes, YouTube updated the internal HTML of the page there and even more they use a/b testing, it's working for some accounts as before and others have a new layout.
I've added support for both layouts, it's on review in browser stores. I'll let you know when it'll be available.

**Comment by NabokD** [comment]
The new version 16.2.7 is available for Chrome and Edge
