### ISSUE TITLE
[Feature Request] "Delete video" playlist's feature

### ISSUE THREAD

**Issue by evd316** [NabokD/pockettube#112]
Pls, return "Hide/Delete video" function to 'Options ⋮' of playlist. This is very useful for removing already watched videos from the playlist.
![Безымянный](https://github.com/user-attachments/assets/e32d3260-a712-423d-b1a2-c442e57633f5)

**Comment by evd316** [comment]
_From correspondence with 'Dima from PocketTube':_

"By the way, the playlist "PocketTube: Youtube Subscription Manager YYYYY-MM-DD" in my playlists section appears either once or much later (in a day I see 1 or 2 old playlists, the current never happens). I guess that's where the link should be taken, but alas, they are not there.
There is such a necessary function of hiding on the subscriptions page. It was also in playlists, but disappeared.
Additional screenshot with my extensions. As I said earlier, to check all but yours were disabled - it didn't affect."

"UPD: If you click on "Play All" in a video of some channel, a playlist is created and displayed in my playlists section, and there is a function to remove from the playlist. The link is there and in the address bar too: [youtube.com/playlist?list=PLEyrJ1NDq652Sr3pzNxrY3vgOtLPnlUK8](https://www.youtube.com/playlist?list=PLEyrJ1NDq652Sr3pzNxrY3vgOtLPnlUK8). True if the playlist is deleted, the link will also become disabled, so I'm not deleting it yet. The same goes for the playlists I created - the 'delete from playlist' function is there.
But if I click on 'Play All' on my subscriptions page (youtube.com/feed/subscriptions), the playlist is created on the current page, but it doesn't appear in my playlists section, or it appears after a while, when it's no longer relevant, because in subscriptions I hide videos that I've watched/not interested in, i.e. I filter them before creating the playlist, and I can do it several times and recreate the playlist by subscriptions. And apparently, until it's there, there's no function to remove videos from the playlist either. Weird.
I assume that a playlist (any playlist) that gets into my playlist section "gets" the delete function, but how to make a playlist created on the .../subscriptions page get into my playlist section immediately and be deleted/updated when a new playlist is created."
![Безымянный1](https://github.com/user-attachments/assets/f948295b-d83d-4afd-8c31-abb2aa8fad99)
![Безымянный2](https://github.com/user-attachments/assets/0f71ccdb-f710-4bcd-aa3a-313054d48313)
![Безымянный3](https://github.com/user-attachments/assets/39e5915b-310e-4903-aa21-67ae24c2da91)
![Безымянный4](https://github.com/user-attachments/assets/83132cb2-6a5b-4551-90e5-a3eb38e8cb45)
![Безымянный5](https://github.com/user-attachments/assets/162d34f2-4702-4364-b13a-833f7ba51c2d)
![Безымянный6](https://github.com/user-attachments/assets/4b28e3e2-80a9-431b-841b-b40fa20dcf4f)
![Безымянный7](https://github.com/user-attachments/assets/68de3d2b-1bb6-4b4a-90ca-4f79bada92df)

**Comment by NabokD** [comment]
It's "Delete video" provided by YouTube, PocketTube has no impact on it.
