### ISSUE TITLE
Latest Safari Update Version 18.0 (19619.1.26.111.10, 19619) breaks upload/download functionality

### ISSUE THREAD

**Issue by stkjj** [NabokD/pockettube#116]
Updating to Mac Sonoma 14.7 which includes a.m. Safari Version breaks pockettubes ability to export/import settings and upload own images for groups.

I recon this will also be true for the latest Release of MacOS Sequioa 15.0.

**Comment by NabokD** [comment]
What extension version are you using? Did you download it from our site?
Try to use direct link to import https://www.youtube.com/#ysm_import is it working?

**Comment by stkjj** [comment]
solved - I used the AppStore Version which apparently is outdated.

**Comment by NabokD** [comment]
Yes, unfortunately, Apple is not allowing an update extension on the App Store, and there you can see the outdated version, they don't like Patreon, and want to replace it with their internal payment system. Also, they don't provide a way to migrate my current Patreon users to their system, so I decided to host the latest version directly on my site, without the Apple store.
