### ISSUE TITLE
Bug? / Backup export error (Arc Browser-win

### ISSUE THREAD

**Issue by Rsfinder** [NabokD/pockettube#117]
thank you so much for continuing to provide PocketTube
now, my youTube would not be what it is without it

just one problem to report. currently in Arc, nothing happens when I export a backup
im sure this is an issue on the Arc side and not PocketTube, but if you can reproduce this issue, please fix it so I can export

i will continue to use and support you🤝

**Comment by NabokD** [comment]
Thank you for sharing! I'll investigate and back to you.

**Comment by NabokD** [comment]
It was an Arc issue, I've added compatibility on the extension side. The new version 16.3.1 is available on the Chrome store, please try to use

**Comment by Rsfinder** [comment]
thanks for the correction!  i was able to export
ill report back if there are any more errors
