### ISSUE TITLE
"PocketTube - Playlist" vs "XYZ 2024-10-27"

### ISSUE THREAD

**Issue by KrzysztofNawara** [NabokD/pockettube#121]
When I use "Play All" button, sometimes the named playlist "PocketTube - Playlist" is updated with the new content and the full number of videos (200, 500, ...). But in other cases, an emphemeral playlist suffixed with the current date is created. What determines which strategy is chosen?

![image](https://github.com/user-attachments/assets/38092653-7281-4df9-a927-3ad5b35e897d)

![image](https://github.com/user-attachments/assets/dabe3a78-fe12-4022-9f39-c2508226b564)

This string of errors seems to happen in a scenario where the limited, 50-video playlist is created:
![image](https://github.com/user-attachments/assets/0d8a1aec-d3be-4a37-99c2-16de503d7dbd)

This is what seems to happen when it works as it should
![image](https://github.com/user-attachments/assets/6a459419-9671-4dce-81bb-e12e9c1040ca)

**Comment by NabokD** [comment]
When you set 50 videos, we create an Unlisted playlist with a date, it's not require a YouTube account and is available by link. 
When you set 100, 200, and 500 we create a Private playlist, it requires your account.

Also, we have a fallback strategy, if a Private playlist is not created for some reason, we'll try to create an Unlisted. It seems your case.
