### ISSUE TITLE
Error 400: unsupported_response_type

### ISSUE THREAD

**Issue by MAmrollahi** [NabokD/pockettube#122]
![image](https://github.com/user-attachments/assets/e3b82deb-396b-460b-ae60-9d3db637d4d2)
![image](https://github.com/user-attachments/assets/3117d1c3-fe20-4060-9590-fe88365b9671)

i got Access blocked: Authorization Error when i tired to resync with google drive

**Comment by NabokD** [comment]
It seems you have conflict with other extensions, which replace URL string, try to disable it
