### ISSUE TITLE
Remove link to Apple App Store

### ISSUE THREAD

**Issue by mjgardner** [NabokD/pockettube#124]
> Apple is not allowing an update extension on the App Store, and there you can see the outdated version [...] I decided to host the latest version directly on my site, without the Apple store

_Originally posted by @NabokD in https://github.com/NabokD/pockettube/issues/116#issuecomment-2376541493_

If you are no longer supporting the App Store version, please remove the “Download on the App Store” button from your site.

**Comment by NabokD** [comment]
Download on the App Store is a link to our iOS app, it's not related to the Safari extension. It's actual and working. The iOS app is free and no restrictions from Apply.

**Comment by mjgardner** [comment]
> Download on the App Store is a link to our iOS app, it's not related to the Safari extension. It's actual and working.

I apologize; the link opened to the App Store on my Mac and I missed the fine print there that says, “Designed for iPad. Not verified for macOS.”
