### ISSUE TITLE
Remove unsupported Apple App Store versions

### ISSUE THREAD

**Issue by mjgardner** [NabokD/pockettube#125]
> I decided to host the latest version directly on my site, without the Apple store.

_Originally posted by @NabokD in https://github.com/NabokD/pockettube/issues/116#issuecomment-2376541493_

Please remove any unsupported apps from the store so that users are not frustrated when bugs remain unfixed:

- [ ] remove [PocketTube for Mac Safari](https://apps.apple.com/us/app/pockettube-for-safari/id1533703891)
- [ ] remove [PocketTube Playlist for Mac Safari](https://apps.apple.com/us/app/pockettube-playlist-for-safari/id1592569440)
- [ ] remove [PocketTube Subscription Manage for iPhone, iPad, and Apple Silicon Mac](https://apps.apple.com/us/app/pockettube-subscription-manage/id1475688814)

**Comment by NabokD** [comment]
PocketTube Subscription Manage for iPhone, iPad, and Apple Silicon Mac is working and up to date, no need to remove it.

I'm not sure makes sense to remove extensions. I hope Apple changes the policy in the future and we'll update it
