### ISSUE TITLE
Grey space in front of groups in Firefox

### ISSUE THREAD

**Issue by KatrinIhler** [NabokD/pockettube#13]
Ever since starting to use Pockettube, I have a grey space visible in front of each group in the left-side display:

![pockettube](https://user-images.githubusercontent.com/11960278/147850828-cf7c95aa-b0d3-4acb-a0ae-791a47095282.PNG)

This grey space does not appear when creating a new group, but will be there as soon as I reload the page. It is also visible when not using dark mode (though not as much).

I use Firefox (currently version 95.0.2) on Windows 10 with version 10.3.10 of Pockettube. I have tried deactivating all other browser add-ons to see if there is interference, but the problem persists.

The space seems to be the in the spot where you can grab on to move groups, but I assume it's not supposed to stand out like this? At least it doesn't in the official screenshots. :D

Please tell me if you need additional information. :)

**Comment by NabokD** [comment]
It is expected behavior for custom sort. You should click on 3 dots(top right corner on your screen) and change sort data. Another way you can lock position in the custom sort view. Watch the tutorial: https://www.youtube.com/watch?v=ToRWfgEh0CE

**Comment by KatrinIhler** [comment]
Oh, the position locking is very helpful! I kept looking at the group options instead of the plugin settings, did not expect that to be there. Either way, thank you for your help! :)
