### ISSUE TITLE
Sidebar scrolling to Subscription Groups on page load.

### ISSUE THREAD

**Issue by alext** [NabokD/pockettube#130]
A recent change has meant that the sidebar always scrolls down to "Subscription groups" on page load, meaning the usual Home, Subscriptions etc links are scrolled out of view. This appears to be because the "Group name" input box is focussed causing Chrome to scroll it into view.

PocketTube version: 16.5.0
Chrome: 131.0.6778.140
MacOS: 15.2

**Comment by NabokD** [comment]
You can create an empty group and reload page after that the input box will not be visible

**Comment by alext** [comment]
Great, thanks. That solves the issue for me.
