### ISSUE TITLE
All toggle switch not updating video list

### ISSUE THREAD

**Issue by sqwirral** [NabokD/pockettube#14]
The `All` toggle button, on the right of this screenshot, doesn't update the video list when toggled. All of the groups switch between green and red visually, but the video list doesn't change.

![image](https://user-images.githubusercontent.com/243372/149790451-f47de47b-856e-4701-ac51-08a909212dcc.png)

A workaround I've found is to click `Hide live` on and off again. This causes the video list to update. Toggling any of the individual groups also causes it to update.

The bug first appeared for me with the release of the Youtube Deck feature, but I hadn't updated PocketTube in a little while before that so maybe it appeared slightly earlier.

Using Firefox 96.0.1 64-bit and also earlier versions.

**Comment by NabokD** [comment]
Thank you for letting me know.
I'm going to redesign the filters. It will be simplified in the new version.

**Comment by NabokD** [comment]
The new version is available on 11.1.8. Try to use it now!

Tutorial video: https://www.youtube.com/watch?v=9RUz3lvGW-8
