### ISSUE TITLE
"Water Later" button stopped working

### ISSUE THREAD

**Issue by chorong761** [NabokD/pockettube#16]
When I hover to a video and click the clock icon to save the video to my watch later list via a subscription group, it would say "saved to watch later" but it actually does not. Clicking watch later at other places work (e.g. recommended videos, within the video page)

Chrome 101.0.4951.67
Windows 11
Extension version 11.2.6

**Comment by NabokD** [comment]
YouTube has changed API. I've prepared a fix and it'll be available after approving the new version soon in stores. 

The new version has been available for Chrome, Safari, and Opera. Waiting for review from Firefox and Edge.

**Comment by chorong761** [comment]
Thank You!

**Comment by NabokD** [comment]
The new version has been available for any browser
