### ISSUE TITLE
Customize sort order in left playlist pane.

### ISSUE THREAD

**Issue by Helmoes** [NabokD/pockettube#17]
Hi, it seems that the playlists in a group in the left pane sort in a weird way. It would be nice to customize this, for example to put a much used playlist at the top in a group. I tried to find out how YT sorts them, but couldn't find any logic. Images added show unwanted behavior. It's also not sorted alphabetical (see image 2)
<img width="199" alt="Screenshot 2022-05-22 024749" src="https://user-images.githubusercontent.com/61212162/169674024-fbf73e81-3ac0-43e8-ba6d-44b0a6870563.png">
![Screenshot 2022-05-22 025227](https://user-images.githubusercontent.com/61212162/169674025-7a1f7891-9f42-487f-a714-03a57dd09843.png)
.

**Comment by NabokD** [comment]
Hi, thank you!
Yes, it is on the long-term plan. I'll notify you when it's available.

**Comment by NabokD** [comment]
It is will be available in the next update in several days.

**Comment by NabokD** [comment]
It is available:
[](https://youtu.be/VWZ72C2pfRU?t=51)
