### ISSUE TITLE
Instagram Accounts Following Manager

### ISSUE THREAD

**Issue by mishradebashis7** [NabokD/pockettube#19]
I am looking for a pocket tube like option to manage/categorize the instagram accounts I am following. Any suggestion help @NabokD ? OR if you can make such feature in this app or any other it will be really helpful

**Comment by NabokD** [comment]
PocketTube has permission only for the YouTube site. So it may be implemented only as a separate extension, but I don't have a plan for implementing it. Maybe I'll do it in future
