### ISSUE TITLE
translation platform very bad

### ISSUE THREAD

**Issue by urfausto** [NabokD/pockettube#2]
currently you can't even access main page.

![2021-08-13 12 09 06 translations yousub info 44ac193db5fe](https://user-images.githubusercontent.com/31393590/129393434-1d79ea53-dcdf-48f8-8bd0-d0431d4b57e1.png)

**Comment by NabokD** [comment]
Hi,  urfausto

Sorry about it. I've made some updates in the time for improving pushing to repositories. Now it is back to live.

**Comment by NabokD** [comment]
Please let me know if you have any more questions or need a hand with anything.
