### ISSUE TITLE
Latest version on latest chrome messes up loading gmail and google drive

### ISSUE THREAD

**Issue by buffos** [NabokD/pockettube#22]
Chrome version : Version 103.0.5060.114 (Official Build) (64-bit)
PocketTube: YouTube subscription 11.4.1

When the extension is enabled, Gmail and Google Drive do not load correctly. When disabling the extension everything works fine

**Comment by buffos** [comment]
Probably something on my end. After restarting the pc 2-3 times and clearing cache few times. It now works fine. Sorry for the post

**Comment by NabokD** [comment]
Yes, I think it is not related. My extension can't change something on Gmail and Google Drive because it is restricted by browser permission. PocketTube has access only to youtube.com
