### ISSUE TITLE
Mac Safari version not working anymore

### ISSUE THREAD

**Issue by andreltr** [NabokD/pockettube#23]
Hello,

I'm not sure what happened but the subscription groups on the left pane disappeared. I reinstalled it and not happened. My configuration is Version 15.6 (16613.3.9.1.7, 16613) on macOS Big Sur 11.6.8 (20G730). Thanks for any help.

Regards,

Andre Luiz

**Comment by NabokD** [comment]
Hello Andre, 

It is a Safari issue. They know the issue and working on a fix to resolve it.

I have a workaround. Try to run the below command in the terminal and restart your computer: 
`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/[Safari.app](http://safari.app/)
`
It forces the extension registration to update.
