### ISSUE TITLE
Subscriptions page not loading more than ~100 videos per channel

### ISSUE THREAD

**Issue by Flipkaboom** [NabokD/pockettube#24]
Plugin version: 11.5.2

When scrolling down far on the subscription page no more than around 100 videos will load per channel. This means that when i scroll down far enough less and less channels will actually show their videos in the list until evetually barely any videos load. 

Steps to reproduce:

- Make a subscription group with 1 channel
- Go to subscriptions page and filter to only show that subscription group
- scroll down, eventually videos will stop showing (see image)
![image](https://user-images.githubusercontent.com/32464794/182660567-262cfc45-8d59-4ac2-9036-014dcdfbb1b4.png)
This channel shows up to exactly 100 videos

When adding another channel to the subscription group 205 videos will load, 100 from the first one and 105 from the second. The amount of videos loaded seems consistent for every channel. Even when filtering with a subscription group with about 50 channels it will only load the last 100 uploaded videos for the channel shown in the image. All others channels in this group will also stop showing up after about 100 videos.

### In a subscription group with 2 channels:
After 100 videos from channel 'Duncan' have loaded it will stop showing their videos:
![image](https://user-images.githubusercontent.com/32464794/182661901-5c73b1f6-d799-47e6-842f-6bfd1f1be900.png)

After 105 videos from channel 'YOGSCAST Lewis & Simon' have loaded their videos will also stop showing up:
![image](https://user-images.githubusercontent.com/32464794/182662086-9bbfcc19-d828-4b7f-bec1-528817504927.png)

**Comment by NabokD** [comment]
It is expected behavior. In this mode, PocketTube hides video using filters. If YouTube doesn't show all videos on the page, we can't change it.
