### ISSUE TITLE
Dark mode is broken

### ISSUE THREAD

**Issue by nzall** [NabokD/pockettube#25]
I just refreshed my Youtube Subscription page and it looks like this: 
![image](https://user-images.githubusercontent.com/6772095/186762812-b47b9ca8-9cc5-4d6e-a866-c342bfd1651a.png)

I'm using PocketTube 11.6.0 from the Chrome store and Edge 104.0.1293.63.

**Comment by NabokD** [comment]
It is a youtube update. I've prepared a fix and waiting for a review new version. It takes up to a day to approve in-store. So I'll notify you when it'll be available.

**Comment by ArkhamCookie** [comment]
Not sure if you need it considering it's an issue on YouTube's end, but I can confirm the issue is also in FireFox.

**Comment by traviss64** [comment]
> Not sure if you need it considering it's an issue on YouTube's end, but I can confirm the issue is also in FireFox.

Yep. On Brave and Firefox same issue

**Comment by NabokD** [comment]
The new version 11.6.3 is available. Try to use it!

**Comment by nzall** [comment]
@NabokD Could you also push that update to the Microsoft Edge extension store? It appears that version is still 11.5.2, and that's what I seem to use on my work account.

**Comment by NabokD** [comment]
> @NabokD Could you also push that update to the Microsoft Edge extension store? It appears that version is still 11.5.2, and that's what I seem to use on my work account.

Yes, I sent it on review yesterday.
Microsoft Edge has a very lengthy review process. It usually takes 7-business days to review. So I hope it will be available by the end of the following week. I can't speed up the process.
The new version is available for other browsers (Chrome, Firefox, Safari, Opera).

As a workaround, you can use an extension from the Chrome web store in Edge and move your data. Click on extension icon -> backup -> export and save the file. After installing the Chrome extension, you can import the file.

**Comment by almahari** [comment]
@NabokD, better to add the theme as a configuration to the extension so that in case there is a change in youtube, it will not break it.

**Comment by NabokD** [comment]
Version 11.6.3 is available for Edge too
