### ISSUE TITLE
New video count resets on page refresh

### ISSUE THREAD

**Issue by alejomedia** [NabokD/pockettube#26]
I've been trying the Firefox extension and noticed that the new video count (the numbers next to a group in the sidebar) and the blue "new activity" dots next to channels seem to reset/clear whenever I reload the page, or leave YouTube and return. This can make it easy to accidentally miss a new upload, especially if I'm only on YT briefly and don't review the sidebar before leaving.

I've reproduced this issue on Chrome as well with no other extensions running, so I wonder if this is the intended behavior? If it is, I'd like to suggest making it an optional toggle in the settings menu, something like "preserve new video count unless channel is clicked on/marked as seen" which would be closer to YT's default behavior.

Love the extension, thanks for all you do.

**Comment by NabokD** [comment]
This information was parsed from the default YouTube subscriptions block. So if this block hides some indicators, an extension can hide too. Also, it hides when you open the channel page.

**Comment by alejomedia** [comment]
Interesting ... but: if the extension is disabled (or not installed) then the default YouTube subscriptions block will _only_ hide the indicator if the channel page is opened. With the extension installed, it is hiding those indicators on page reload even when I did not engage with the channel at all.

**Comment by NabokD** [comment]
It can be if you open the feed(tv icon near group name) or use a filter with auto tags. In this case, it will be marked as watched.

**Comment by NabokD** [comment]
Hi

Try to use the latest version 12.0.6. Some users have a new YouTube layout(rounded) and new video count was hidden

**Comment by alejomedia** [comment]
Yes, it's working great now. No issues to report. Thank you!
