### ISSUE TITLE
Default subscription item appears as a last item in the sidebar

### ISSUE THREAD

**Issue by Acid-Crash** [NabokD/pockettube#27]
Hi here.
When using a PocketTube, the default subscription item shifts to the bottom of the sidebar.
This happens in 80% of cases, refreshing the page does not help this issue.
Once I disable the extension and reload the page, the position of the items within the sidebar becomes normal.

Here is a quick demo.
Please notice that first there are some additional items below the default subscription (What's new, Settings etc).
Next, after activating the extension and refreshing the page, these elements appear before the default subscriptions

All-in-All, I expect that default subscription should retain its position within the structure when PocketTube is active

My setup:
Win10x64
Firefox 104.0.2 (64 bit)
PocketTube v12.0.3

![PocketTube](https://user-images.githubusercontent.com/32600318/190794679-a972c41a-e075-4293-bf5f-f57c7c8b27e0.gif)

**Comment by NabokD** [comment]
Thank you for letting me know! I'll investigate the behavior because in my case it works properly. I'm back in several days.

**Comment by NabokD** [comment]
I've found an issue and solved it. I'll add it to the next release and notify you when it will be available.

**Comment by Acid-Crash** [comment]
Hi,
Thank you for the quick feedback.

**Comment by NabokD** [comment]
The new version 12.0.4 is available. Try to use it.

**Comment by Acid-Crash** [comment]
Confirming. 
The issue seems to be fixed in the latest update.
Thank you for such great extension!
Should I close this request?

**Comment by NabokD** [comment]
Glad to hear!
