### ISSUE TITLE
Unpleasant scroller showing on left sidebar in YouTube due to added content

### ISSUE THREAD

**Issue by apoapostolov** [NabokD/pockettube#32]
I have a big issue with a white scrollbar showing on the left sidebar, most unpleasant while using the dark theme, when PocketTube adds a lot of content to the sidebar, such as a very long list of subscription groups.  If I click on the three-dotted menu of Subscription groups and pick an option, the sidebar may disappear until the page is reloaded, but there should be some CSS fix to make sure it never appears.

![image](https://user-images.githubusercontent.com/4083812/193888568-421dc178-0362-4089-9bec-c0802fa54842.png)

Слава Украине!

**Comment by apoapostolov** [comment]
The problem can be fixed with using YouTube Material CSS by https://github.com/RaitaroH/YouTube-DeepDark and using Enhancer for YouTube Chrome extension that will inject that theme into YouTube but probably fixing it via PocketTube will make it much better for all users.

**Comment by NabokD** [comment]
It is weird. I can't reproduce it. What browser are you using? Try to disable other extensions maybe you have a conflict with something. If you detect it, please let me know.

**Comment by NabokD** [comment]
Maybe do you use specific settings in Enhancer for YouTube? Because in my case, it looks like default.
<img width="250" alt="Screenshot 2022-10-04 at 20 45 57" src="https://user-images.githubusercontent.com/10400731/193889716-88601f58-90cf-46ac-9aa6-ba5f7219a352.png">

**Comment by apoapostolov** [comment]
The problem happens when I'm not using Enhancer, only PocketTube. Enhancer solved the problem for me by forcing a complete custom theme.

I'll try with a clean environment later today with only PocketTube and report back

**Comment by NabokD** [comment]
Any updates about this issue? I didn't get similar requests latest few weeks.
