### ISSUE TITLE
Channel playlist button throws an error and won't open

### ISSUE THREAD

**Issue by iveanissue** [NabokD/pockettube#35]
There's a bug preventing PocketTube's channel playlist button from opening.
It throws an error when I click on the button which I can see in the console. 
![image](https://user-images.githubusercontent.com/99297074/195991293-ccef3b56-eff7-4973-935a-8b5fc7812b01.png)
![image](https://user-images.githubusercontent.com/99297074/195991299-74542759-3bf4-4de6-b0b0-63b6ea40e541.png)
The script is compressed, so I don't know where the actual line in the source code is.
I checked and confirmed that it's coming from `moz-extension://{PocketTube UUID}/build/app.js`.
The piece of code that is throwing the error looks like this:
```js
document.querySelector(".ysm-group-popup-in-list .ysm-collection-name").focus()
```
Since `querySelector` is returning `null`, an error is thrown when trying to call the method `focus` on it. 

I'm using **PocketTube 12.1.2** on **Firefox 105.0.3** on **Windows 10**.

**Comment by iveanissue** [comment]
The problem seems to be because I didn't have any Subscription Groups. Maybe some sort of warning message when you click on the button without any Groups would be helpful here.

**Comment by NabokD** [comment]
Thank you for letting me know. I'll fix it in the next version, it looks like the left sidebar is hidden, and for this reason, the script can't find the element. I'm going to add an alert here.

**Comment by NabokD** [comment]
It was fixed in prev versions
