### ISSUE TITLE
Unable to sign in to Google for Drive backup

### ISSUE THREAD

**Issue by qstar-inc** [NabokD/pockettube#36]
I'm on Firefox 107.0b4, Windows 10 21H2
I tried to enable the "Sync data with Google Drive" option.
After I clicked the "Enable" button, a new tab opened to prompt me to select the Google account I want to use (I have two).
![image](https://user-images.githubusercontent.com/11435876/197540917-ded36e9d-9f16-4112-a47e-f35527109c0c.png)
After that it prompts me to select my "account or brand", aka my YouTube channel, where I choose my primary channel.
![image](https://user-images.githubusercontent.com/11435876/197540977-94956097-a196-4143-abdb-685ed46b783e.png)
But instead of succeeding, I get an error.
![image](https://user-images.githubusercontent.com/11435876/197541078-a566d54e-268e-42aa-a6cc-843cb99acef6.png)
The "Next" button shows a 400 error.
![image](https://user-images.githubusercontent.com/11435876/197541210-4f9547d8-bd85-492c-bd0c-408d42d1e77c.png)

**Comment by NabokD** [comment]
It is weird, try to login/logout from google account.
