### ISSUE TITLE
Subscription Groups -> Unwatched not working

### ISSUE THREAD

**Issue by Nydid** [NabokD/pockettube#4]
- Made a Subscription group of Music channels
- Went into said group
- Clicked "Unwatched" sorted by "Date Added (Oldest)"
- Set video count to 500
- Clicked on big "Play All" button
- Got a playlist of 50 videos
- Watched all the 50 videos
- Went back to Subscription Group back and "Unwatched" still has all the watched videos

1 - Is it normal behavior for the playlist to only have 50 videos if it's "Set video count" is 500?
2 - Anyway to fix the unwatched issue?

Cheers!

**Comment by NabokD** [comment]
Did you log in on youtube?

1. For playlist over 50 videos the extension use internal youtube API using your current account. If it is not successful for some reason, I make a fallback using a URL-based playlist. It has 50 videos.
2. PocketTube doesn't save 'unwatched' status in extension, I'm getting it from youtube channel data.
It depends on the youtube viewing history feature: youtube.com/feed/history You have to enable it for working with the feature.

Please let me know if you have any more questions or need a hand with anything.

**Comment by Nydid** [comment]
> 
> 
> Did you log in on youtube?
> 
>     1. For playlist over 50 videos the extension use internal youtube API using your current account. If it is not successful for some reason, I make a fallback using a URL-based playlist. It has 50 videos.
> 
>     2. PocketTube doesn't save 'unwatched' status in extension, I'm getting it from youtube channel data.
>        It depends on the youtube viewing history feature: youtube.com/feed/history You have to enable it for working with the feature.
> 
> 
> Please let me know if you have any more questions or need a hand with anything.

I was always logged into Youtube while using the extension
1. Logged in, don't understand what makes it fallback to URL based
2. History is enabled, I can see the videos I watched in there, but the extension still doesn't mark them "Watched"

**Comment by NabokD** [comment]
1. It is a fallback that doesn't use your account to generate a playlist and has a limit of 50 videos.
2. Do you see the red watched line on the channel page after watched some video? I collect watched status from the channel page. Try to disable other extensions. Maybe you have a conflict with something.

**Comment by Nydid** [comment]
I see a red line everwhere (History, on Channel page, on Homepage), every extension but Pockettube is disabled, firefox restarted. Nothing works

**Comment by NabokD** [comment]
I tested it in Firefox and reproduce it. It looks like an issue only on Firefox or youtube version for firefox. It is related to generating auth a header in Firefox. Youtube on Firefox consider is incorrect.
I'll keep researching it.

**Comment by NabokD** [comment]
Great news! I found the solution how to fix it.
I've fixed it in version 9.9.25 and am awaiting approval from the Firefox team. It takes several days. I'll notify you after it will be available.

**Comment by NabokD** [comment]
New version 9.9.25 is available. Try to use it now!

**Comment by Nydid** [comment]
> 
> 
> New version 9.9.25 is available. Try to use it now!

Everything works :D 
I don't need to rely on a second extension to hide Watched.
Thanks!
