### ISSUE TITLE
Cannot launch app from app drawer or homescreen

### ISSUE THREAD

**Issue by MdXMaxX** [NabokD/pockettube#40]
Hello,

I noticed today that when I try to launch the PocketTube app from either my app drawer or homescreen shortcut, I get a "Permission denied" error.  However, I can open the app if I go to the "App Info" page and open it from there.  I didn't see this issue a few days ago, so it seems related to the latest update.

I'm using Nova Launcher on my Samsung Galaxy S21 with Android 12.

Un-installing and re-installing the app does not seem to fix the issue.  I don't see this issue with any other apps.

Any help would be much appreciated.

Thank you.

![image](https://user-images.githubusercontent.com/762285/203667707-09a057ae-9f38-415f-ba54-eaead540f9a9.png)

**Comment by NabokD** [comment]
Try to use the latest version 2.0.43

**Comment by MdXMaxX** [comment]
Great, the latest version fixes the issue.  Thank you!
