### ISSUE TITLE
Filter doesn't hide watched videos after lazy loading

### ISSUE THREAD

**Issue by zapp2me** [NabokD/pockettube#41]
I just noticed a weird behaviour on the subscription page.
I always uncheck the filter "watched" so only new videos are shown on this page.

For a couple of days now, I noticed a lot more watched videos on the site (red bar beneath the thumbnail) that should be hidden.

I think the issue is, that YouTube loads additional videos (lazy loading) after the top ones I already watched are hidden by pockettube. But the reloaded videos are not hidden.

So I got empty segments for "Yesterday", "This week", "This months", because I already watched all the videos for the segment - but beneath that are a lot of videos I already watched that where lazy loaded.

Hopy this makes sense.

**Comment by NabokD** [comment]
Thank you for sharing. I'll investigate it next week

**Comment by NabokD** [comment]
It's available in version 14.0.0
