### ISSUE TITLE
[Issue] Subscribed Channel -> Videos -> Filters

### ISSUE THREAD

**Issue by VeNoMouS** [NabokD/pockettube#42]
When filtering "watched" videos out , it does not re-align / clean up the display when it removes watched videos...

![image](https://user-images.githubusercontent.com/597545/204435412-96a4fec1-c26b-45ee-bd67-450d2cd54d8b.png)

this is what it looks like without being filtered..

![image](https://user-images.githubusercontent.com/597545/204435473-a44112a6-8870-4f61-ad74-916c082354ec.png)

**Comment by NabokD** [comment]
It is expected behavior after the latest YouTube update.

**Comment by VeNoMouS** [comment]
rgr that then..
