### ISSUE TITLE
Select multiple individual videos in playlist.

### ISSUE THREAD

**Issue by Aquilux** [NabokD/pockettube#44]
Feature request: enable group selection of videos individually inside a playlist (instead of filtering by tag or length) to enable group actions like move or delete.

Use case: I want to delete from a playlist, for instance, videos 1, 2, 3, 5, and 8, but not 6, 7, 9, 10, ect. They do not have a group in common that is not applied to other videos I do not want to delete.

Expected: In playlist view check box or ctrl+click to highlight multiple videos individually, and not necessarily sequentially, to then be deleted.
Alternative: under "playlists" tab, allow expansion of a playlist to show contained videos for individual selection as mentioned above

Actual: Can only select videos by filtering category or length. Can only group delete videos from playlist that are selected via filter. Can select multiple playlists in "playlist" tab for multi-deletion, but can not do the same for individual videos in playlist as clicking on playlist only opens the playlist for viewing. Only way to remove a select set of videos from a playlist remains google's absurd one-at-a-time multistep deletion process.

**Comment by Aquilux** [comment]
Would apply feature request label if I knew how.

**Comment by NabokD** [comment]
It is available, watch the tutorial: https://youtu.be/fEeOfUWpT84?t=32 or do you mean something another?

**Comment by Aquilux** [comment]
My apologies, I seem to have either missed this functionality or not had it load for me prior to my request. I have since been able to use the function and it satisfies the need. IIRC the belief that the function did not exist came from my not seeing/not remembering seeing the functionality mentioned in the onbording when first opening youtube after installing the plugin.
