### ISSUE TITLE
When assigning channels to a group the browser keeps on reloading the page

### ISSUE THREAD

**Issue by 4sthea** [NabokD/pockettube#47]
I'm using Unlock, Youtube Enhancer, Pockettube Youtube Playlist Manager and Pockettube Youtube Subscription Manager. When I add a channel to a group in the Subscription Manager, the Youtube page keeps on reloading indefinitely. When I deactivate the Subscription Manager, it stops. I deactivated my other 3 Youtube extensions, the problem doesn't dissapear, so it must be a Subscription Manager exclusive problem.

Is this a bug or is there a workaround for this problem?

**Comment by 4sthea** [comment]
Oh and I'm using Chrome.

**Comment by NabokD** [comment]
I can't reproduce it and don't have similar requests. Try to disable all extensions which have access to the YouTube page, it seems like conflicts with some of them. Also, try on clear browser, it's not a problem of PocketTube.

**Comment by 4sthea** [comment]
Ok I'll give it a try. :)

**Comment by 4sthea** [comment]
Ok I think I found out why. It seems to have been done by the Unhook addon:
![image](https://user-images.githubusercontent.com/127614065/224495974-f0d7746c-f58c-4e05-9566-96f9a31d8a21.png)

If I deactivate the "Hide Explore, Trending" option, it seems to be working again. For the Playlist Manager, I additionally have to deactive the "Redirect to Home Feed", otherwise when I click on a playlist, I get redirected to my subscription feed instead of the playlist itself.
