### ISSUE TITLE
Subscription group popup in loading state forever

### ISSUE THREAD

**Issue by Zz9uk3** [NabokD/pockettube#5]
Firefox version: 91.0.2 (64-bit)
PocketTube version: 9.9.22
Other extensions: None

**Screenshot:**

![image](https://user-images.githubusercontent.com/16165569/132059761-898398a1-c35b-4b63-8c73-366c1a46c65b.png)

**Firefox console log:**
https://gist.github.com/Zz9uk3/cdc9909d8705a7057d63894afc92a293

Thanks for this awesome extension, i love it.

**Comment by NabokD** [comment]
Hi

Thank you for the message! Sorry about it. Looks like the bug in the latest Firefox version. I've prepared a new version of 9.9.23 and am awaiting approval from the Firefox team. It takes several days. I'll notify you after it will be available.

Temporary solution: open the page: https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-groups/versions/ and click 'Download file' on version 9.9.18. After that, it'll be working.

**Comment by Zz9uk3** [comment]
Thanks for the very fast reply. Switching back to the older version fixed it

**Comment by NabokD** [comment]
New version 9.9.23 is available. Try to use it now!
