### ISSUE TITLE
PocketTube keeps redirecting to home page when trying to watch the video

### ISSUE THREAD

**Issue by RoonMoonlight** [NabokD/pockettube#50]
Hello, the PocketTube keeps redirecting to home page when trying to watch the video and it is really annoying bug.

The list of extensions currently using:
* [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
* [Bitwarden](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb)
* [DeepL](https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj)
* [LibRedirect](https://github.com/libredirect/libredirect)
* [Enhancer for YouTube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle)
* [FastForward](https://github.com/FastForwardTeam/FastForward)
* [Holodex Plus](https://chrome.google.com/webstore/detail/holodex-plus/mjcecbpccklceljomllkhilglcdcncbh)
* [HyperChat by LiveTL](https://chrome.google.com/webstore/detail/hyperchat-by-livetl/naipgebhooiiccifflecbffmnjbabdbh)
* [LiveTL](https://chrome.google.com/webstore/detail/livetl-translation-filter/moicohcfhhbmmngneghfjfjpdobmmnlg)
* [Unhook](https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid)
* [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)
    * [NamuLink](https://github.com/List-KR/NamuLink)
    * [microShield](https://github.com/List-KR/microShield)
    
Currently, the Unhook is suspicious because it might be the cause which keeps redirecting to subscription page.

**Comment by NabokD** [comment]
Yes, Unhook can do it. Try to disable it.
I would say it's not a PocketTube issue because, in my extension, there is no logic to redirect to something or reload the page. The issue is on another extension side. Try to disable them one by one.
