### ISSUE TITLE
Not unsubcribing from channels

### ISSUE THREAD

**Issue by gguy825** [NabokD/pockettube#52]
Ive used this to purge around 200 channels but it hasn't unsubscribed from any of them at all. Im on the latest firefox build 111.0.1.

**Comment by NabokD** [comment]
It's weird. Maybe Youtube restricted too many unsubscribes at once as suspicious. Try to unsubscribe small batch.
I tested it just now on my account with 30 channels, it was working fine.

**Comment by gguy825** [comment]
Update - slow batches work best now. My sub count has finally been going down so could just be youtube limiting how many channels you can actually unsub to at once maybe?

**Comment by NabokD** [comment]
Yes, I think youtube has limits for this, but there is no public info about it.
