### ISSUE TITLE
[April Update] Subscription page filters have stopped working

### ISSUE THREAD

**Issue by utkarshgupta137** [NabokD/pockettube#54]
I have, unfortunately, received an update to my subscriptions page which has broken this extension: 
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/5155100/233577367-209985e8-ff7b-48fa-863f-394bfd81cb54.png">

Normally, I would hide the watched videos & the shorts sections using this extension & also some of the channels.
I had forgotten how useless YouTube is without this extension.

This is on latest Firefox on latest macOS

**Comment by NabokD** [comment]
Hello, it was fixed several days ago. It's available for Chrome/Edge store.
Unfortunately, the version is not available on Firefox yet, and I am still waiting for the review. They review only during the working day. So maybe it will be today or next week.

**Comment by Kzanol** [comment]
Same thing happening on Safari for the Mac...

**Comment by NabokD** [comment]
The new version 15.1.3 is available for every browser

**Comment by NabokD** [comment]
> Same thing happening on Safari for the Mac...

I think you use an outdated version, the latest one is 15.1.3. Download it using the link below:
https://pockettube.io/install/PocketTube.dmg
Unfortunately, Apple is not allowing an update extension on App Store, because they don't like Patreon, and want to replace it with their internal payment system. Also, they don't provide a way to migrate current users to their system, so I decided to host the latest version directly on my site, without the Apple store.

**Comment by utkarshgupta137** [comment]
Is it possible to get the grid fixed?
Also, it would be nice if I could fit more videos in a row.

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/5155100/234978743-85b873a0-3ddc-4565-8303-91cd78567863.png">

**Comment by utkarshgupta137** [comment]
Luckily, I found a Stylus extension: https://github.com/sapondanaisriwan/AdashimaaTube

**Comment by utkarshgupta137** [comment]
@NabokD Home page filters are still missing. Should I create a separate issue?

**Comment by NabokD** [comment]
What do you mean? We don't have home page filters.

**Comment by utkarshgupta137** [comment]
My bad! I saw shorts in my home feed & thought this was a feature.
Thank you for all your hard work!
