### ISSUE TITLE
[Feature Request] More playlist time sort options

### ISSUE THREAD

**Issue by Crunchbits** [NabokD/pockettube#55]
Currently you can sort by

- All
- short - 0-15 minutes
- medium - 15-60 minutes
- long - over 60 minutes

I have a lot of videos in my playlists and sometime I only have time to watch for a super short time, I think a good new option would be
- 0-5 minutes

**Comment by NabokD** [comment]
Thank you for sharing!

**Comment by NabokD** [comment]
It's available for the playlist page, watch the release tutorial
https://youtu.be/lMXKQdGbQbQ?si=DVcsD1xGkb82IK8X&t=24
