### ISSUE TITLE
Missing Mark as Watched icon in new Subscription page UI

### ISSUE THREAD

**Issue by HidyHo** [NabokD/pockettube#57]
I'm a new Patreon paid user for this app.

Under the recently released new YT Subscription page (with larger thumbnails), I can't seem to find the Mark as Watched icon.  I can only seem to manage this function under each Subscription Group which is a slow and inefficient process.  I generally like to do a first sweep/filtering of subscribed videos from the main Subscription page.

**Comment by NabokD** [comment]
Currently, we don't support mark as watched on the new youtube subscription page, maybe it'll be in the future, but I'm still investigating it.

**Comment by NabokD** [comment]
Great news! I've found a way how to back it, it's available from version 15.2.5 on Chrome.

**Comment by NabokD** [comment]
It is on the thumbnail as previously, watch the screenshot:
https://share.cleanshot.com/0SG6M85q

**Comment by HidyHo** [comment]
I figured out why you and I have different outcomes.  

Your way works if the "Inline Playback" setting is ENABLED.  If this setting is turned off, then one just gets "Watch Later" and "Add to Queue" icons without "Mark as Watched" icon.

If possible, I would think the functionality should work both ways.

FYI, I'm on ChromeOS Version 114.0.5735.84 (Official Build) beta (64-bit).

**Comment by NabokD** [comment]
I've found a reason why it's not working without Inline Playback, it'll be available soon.

**Comment by NabokD** [comment]
I've fixed it in version 15.3.1. It's available for Chrome.

**Comment by HidyHo** [comment]
Thanks,  I can confirm that I see the icon now with "Inline Playback" turned off.  Now, only if I can see it under three dots :)

**Comment by NabokD** [comment]
Glad to hear! The context menu is out of the current scope, maybe it'll be some time, however, currently, there is no easy way involve to it.
