### ISSUE TITLE
Broken Grid view 

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [NabokD/pockettube#58]
Im on chrome and the grid view with pocket tube looks like this

![image](https://github.com/NabokD/pockettube/assets/36243865/ed82a66d-f66a-4c6e-b1d0-4648cce6e188)

**Comment by NabokD** [comment]
It's not broken, it's a new YouTube update, there is no way to hide free space after filtering. I can suggest using the PocketTube feed by the group if you want a grid view as before. Watch the part of the tutorial: https://youtu.be/r4iX53Qg2sE?t=232

**Comment by AbrahamArmasCordero** [comment]
so basically because we filter out watched and shorts if we have a group with very few videos, we are not able to reorganize them in rows and colums to fill the whole space.

I don't think this is the experience we want for this Extension, can i help to find a solution?

**Comment by NabokD** [comment]
You can, but I don't see the way how to do it because youtube uses grid ytd-rich-grid-row with 3 items and there is no way to move it.

**Comment by NabokD** [comment]
The new version 15.3.0 is available for Chrome

**Comment by AbrahamArmasCordero** [comment]
wow, went from can't do to flexing in one day AHHAAH
![image](https://github.com/NabokD/pockettube/assets/36243865/53185dc4-9fe6-4972-818a-90574e06c99f)

Great, thanks for the fix, I appreciate it
