### ISSUE TITLE
Subscription group popup automatically jumping to first video channel

### ISSUE THREAD

**Issue by Zz9uk3** [NabokD/pockettube#6]
Firefox version: 91.0.2 (64-bit)
PocketTube version: 9.9.18 (like adviced [here](https://github.com/NabokD/pockettube/issues/5))
Other extensions: None

Sometimes when I open the subscription group popup (clicking at the play symbol next to the group name, screenshot below) Firefox is displaying the popup for a while and then proceeds to redirect me to the uploaders channel of the newest (or better said first) video in the group without any interaction from my side.

![image](https://user-images.githubusercontent.com/16165569/132105113-0a4b5c09-d369-47be-9e2a-49ab929d008e.png)

Its definetly not a really annoying bug and at this point I cant even properly reproduce it but I will report back with logs once I find out more.

**Comment by NabokD** [comment]
Thanks for notifying me! Let me know when you get more details, because I don't have ideas on how to reproduce it.

**Comment by Zz9uk3** [comment]
reporting back on this one :)
it will redirect me whenever a subscription group has new videos (= having a number on the right of the group link).
the log as soon as I click on the group looks like this:
https://gist.github.com/Zz9uk3/fe2519a5209808268b389d417d40f0d4

And the network analysis (found no way to export it so sharing a screenshot):

![grafik](https://user-images.githubusercontent.com/16165569/147082726-c684e001-e507-4354-8e12-20d168aaf241.png)

Interesting part: The NS_BINDING_ABORTED entries point to the different channel urls that uploaded the unseen videos with /playlist appended to it:
1. https://www.youtube.com/channel/UCksZb3UtcbxNn2RoMYnnCbw/videos/playlists
2. https://www.youtube.com/channel/UCtiiCWy8AWAS9o1FsDV-8kg/videos/playlists
3. https://www.youtube.com/channel/UC0JB7TSe49lg56u6qH8y_MQ/videos/playlists

the fourth entry where the GET was not blocked points to the channel I get redirected to:
https://www.youtube.com/channel/UC6y5h-dW-A6RBRHXDPlj9Rg/videos/playlists

I hope this somehow helps you reproduce what is happening here :)

Thanks

**Comment by Zz9uk3** [comment]
Waaait it was all my fault. The Addon "Improve Youtube!" (https://addons.mozilla.org/de/firefox/addon/youtube-addon/) caused the problem. After uninstalling it the redirect is gone.
