### ISSUE TITLE
Main Subscription pages showing "some" watched videos

### ISSUE THREAD

**Issue by HidyHo** [NabokD/pockettube#60]
I have my subscription page set to filter out WATCHED and #SHORTS videos.  

However, the issue is that I am seeing "some" (meaning not all) watched videos.  I believe the watched videos showing up on the subscription page are videos watched from either DECK  or from Subscription Groups.  I believe videos that I watched from the main Subscription page do not reappear.

When I use the "Play all" feature to create a playlist from the main Subscription page, I can see that videos have already been played previously by noting the YT Progress Bar on the bottom of the video.  Perhaps the logic behind WATCHED filter needs refinement?

I think there is a separate(or related?) issue that videos watched from either DECK or Main Subscription page are showing up the Subscription Group so I am not confident that WATCHED filter is working consistently in Subscription, Deck and Groups.

I think PocketTube is a powerful and very useful extension.  With refinement, it can be awesome.

**Comment by NabokD** [comment]
I'm not sure how to reproduce it. Could you please provide screenshots? Did you try to update the pages? In case you watched in different tabs it'll not be updated on previously loaded pages, maybe it's the reason
