### ISSUE TITLE
Filter by video type stopped working

### ISSUE THREAD

**Issue by Arqaen** [NabokD/pockettube#61]
In the subscription group when you try to filter, to remove the shorts videos, its not working anymore.
Maybe youtube had changed something and the code is not recognizing the shorts videos so it cant be filtered.
Will be awesome if this issue get fixed.

**Comment by NabokD** [comment]
Thank you for letting me know. I've reproduced the issue and prepared a fix. I'm waiting for a review new version. It takes up to several days to approve in stores
As a workaround, you should select 'Live', because it's working is not correctly without Live at the current release.

**Comment by NabokD** [comment]
The new version 15.3.5 is available, try to use filters

**Comment by Arqaen** [comment]
> The new version 15.3.5 is available, try to use filters

Thanks, its working now, I have noticed if you don't have a logged in account, the filter doesn't work (in the subscription groups), Can you check that?

**Comment by NabokD** [comment]
> > The new version 15.3.5 is available, try to use filters
> 
> Thanks, its working now, I have noticed if you don't have a logged in account, the filter doesn't work (in the subscription groups), Can you check that?

It's expected behavior, the filters on subscription groups depend on your youtube account.
