### ISSUE TITLE
Videos in the subscription feed don't appear as a grid anymore

### ISSUE THREAD

**Issue by Simon-Guillet** [NabokD/pockettube#62]
Videos used to appear in a full grid, now there are holes everywhere.
I use Firefox. I tested it in Chrome and there was no problem.
Here is the error shown in the console:
`TypeError: this.querySelector(...) is null app.js:2:1264783`

![image](https://github.com/NabokD/pockettube/assets/84067610/081a431f-7dc6-4ae2-9137-e973d68f9017)

![Screenshot 2023-06-14 at 01-36-00 Subscriptions - YouTube2](https://github.com/NabokD/pockettube/assets/84067610/0dcb5754-2ff8-4ad4-8c42-52e2cb9f33a2)

**Comment by NabokD** [comment]
I think you use an outdated version on Firefox. They have a slow review process. The latest one is 15.3.3

**Comment by Simon-Guillet** [comment]
Yes, that was it, thank you.
