### ISSUE TITLE
Only some videos from a particular channel is showing in group feed

### ISSUE THREAD

**Issue by chorong761** [NabokD/pockettube#65]
So, I have [this channel](https://www.youtube.com/c/ChannelCHK) in my subscription group, but in the group feed it would only show a few of the recent videos from a few days ago. I have set the feed to show 500 videos, and it is showing videos up from up to two weeks ago.  Videos from other channels older than a few days are showing properly.

**Comment by NabokD** [comment]
It has a restriction by youtube. The feed is based on the 15 latest videos per every channel. For this reason, in your case, you can't see videos oldest than several weeks if the channel published more than 15 videos recently.
