### ISSUE TITLE
Bookmark always points to the PocketTube folder

### ISSUE THREAD

**Issue by tvrhossain** [NabokD/pockettube#66]
When I want to bookmark anything, the bookmark always points to the PocketTube folder used before, its irritating since I have to change to the other folder every time. It happens after I subscribed to a channel and then assign a group to it, from then on the bookmark always points to that pocket tube folder.

**Comment by NabokD** [comment]
What bookmark do you mean? It's not clear to me. Could you please send screenshots of what you mean exactly?

**Comment by tvrhossain** [comment]
> What bookmark do you mean? It's not clear to me. Could you please send screenshots of what you mean exactly?

I  meant the browser bookmark. After I subscribed to a channel and assigned it to a group, The browser bookmark always points to that pocket tube bookmark folder (for that group). If I want to bookmark any new page, the browser bookmark is always there, so I have to change again

![Snipaste_2023-07-31_15-47-54](https://github.com/NabokD/pockettube/assets/6359871/9373e127-41b4-4e8b-9711-6edbd2e568fe)

**Comment by NabokD** [comment]
Thank you for clarifying! I think there is no way to change it. PocketTube uses internal bookmarks API in Chrome, and it seems to change the latest folder every time. Unfortunately, I don't see available params to make configure it.
As a workaround, you can disable bookmarks on PocketTube and enable them from time to time when you want to sync changes.
