### ISSUE TITLE
Watch History Broken

### ISSUE THREAD

**Issue by Kyzoku** [NabokD/pockettube#68]
As of the 18th of August, videos set as watched on the deck, display a turn on watch history notification.  I have watch history for YouTube turned on.  Videos that have actually been watched are set as watched, so pockettube is reading YouTubes watch history properly, but videos just set as watched (without actually watching) are not being added to the watch history.

**Comment by NabokD** [comment]
It was a YouTube update. What browser are you using? The new version 15.6.6 is available for Chrome and Safari. Other browser stores have a slow review process and it'll be available next week because they don't review on weekends.

**Comment by Kyzoku** [comment]
I'm using Edge.  I switched to the Chrome webstore extension instead and everything works as it should.  I did notice however that the version I have is 15.6.7 not 15.6.6.  Was that a typo on your part, or is the version number on the chrome webstore incorrect?  Thanks again for clarifying this for me.

**Comment by NabokD** [comment]
It's ok, both versions include the fix. Version 15.6.6 was released yesterday with the fix of the bug, and after that today 15.6.7 was released with other improvements.

**Comment by Kyzoku** [comment]
Alright, thank you for your quick replies.
