### ISSUE TITLE
[BUG] Clicking a video in a subscription group, plays it as a list..

### ISSUE THREAD

**Issue by VeNoMouS** [NabokD/pockettube#7]
When you click on a video (chrome) that is under a subscription group, it adds &list=<id> to the URL, thus auto playing videos from said subscription group.

This doesn't seem to do it for all subscription groups which is weird... and i cant  find a way to disable this feature... 

When you mouse over the video it doesn't have the list param... but when you click on it, it redirects with the list param.... 

thanks for the awesome project btw :)

# edit:

it doesn't seem to do it for all videos in the group..

# edit 2

it occurs when you hold control and click the video for in a new tab.. it doesnt do it if you right click and open in new tab... can we remove the list from the ctrl + click?

**Comment by VeNoMouS** [comment]
Looking at the subrredit , i see other people appear to have raised this issue as well


https://www.reddit.com/r/pockettube/comments/pizyqt/i_have_two_issues_with_playing_a_playlistis_this/

**Comment by NabokD** [comment]
Yes, you can remove the &list= link. Click on the extension icon -> and enable 'remove playlist link in TV mode'
Also watch the tutorial video: https://www.youtube.com/watch?v=UUXIZNn7_uU

Please let me know if you have any more questions or need a hand with anything.

**Comment by VeNoMouS** [comment]
blood legend , that sorted it, thank you mate and thank you for the prompt response :) and that video 100% helped
