### ISSUE TITLE
Channels being selected and unselected at random

### ISSUE THREAD

**Issue by martienne17** [NabokD/pockettube#70]
I really like the extension but I've been struggling with the fact that channels will randomly be added or removed from subscription groups without my input. I've been needing to curate the lists almost daily to be able to get them to play the subs I want to see in each list.

**Comment by NabokD** [comment]
It's weird, try to disable other extensions. I can't see any issue with the extension to handle saving data and there are no reports from other users. By default your data is saved in chrome.storage.sync https://developer.chrome.com/docs/extensions/reference/storage/#property-sync Maybe Chrome synchronization is not working correctly but again no report about it from other users
