### ISSUE TITLE
[Bug] PocketTube removes all shorts from the subscriptions feed and completely breaks the /feed/subscriptions/shorts page.

### ISSUE THREAD

**Issue by MPJ-K** [NabokD/pockettube#73]
I noticed that shorts haven't been showing up in my subscriptions feed recently and after some investigation it appears PocketTube is the cause. This issue persists even when all video types are enabled/shown and no filters are set. I am running PocketTube using the Brave browser (chromium).

It seems that YouTube is now displaying shorts on a special shelf that separates parts of the subscriptions feed on both grid and list view. PocketTube completely removes this shelf, which seemingly causes all shorts to disappear from the subscriptions feed entirely.

The shorts shelf also contains a 'View all' button, which takes you to 'www.youtube.com/feed/subscriptions/shorts'. This page normally contains a subscriptions feed for shorts only. With PocketTube enabled, the page is very broken and can only be accessed through the URL because the button is removed along with the shelf. The YouTube sidebar will load, but no shorts are displayed and other parts of the page do not load properly.

It would be great if shorts could somehow be re-integrated into the subscriptions feed. At the very least, PocketTube should not break the normal functionality of the '/feed/subscriptions/shorts' page.

**Comment by NabokD** [comment]
If you enable filters by group, the shorts will be hidden, because there is no way to filter them after the latest update on YouTube. It's expected behavior, if you want to see shorts there you should uncheck all group filters(should be white) and enable all content filters.

PocketTube is not breaking feed/subscriptions/shorts. The page is not working even without PocketTube. It is a bug on the YouTube side because you can't open the page directly by link.

**Comment by MPJ-K** [comment]
Thank you for explaining. Clearly I was not thorough enough in testing the issue.

If shorts do not work with group filters anymore, then would it not make sense to have the '#SHORTS' filter toggle between showing/hiding the shorts shelf regardless of group filters? Perhaps that is not possible to implement?

Regardless, thank you for your work on PocketTube. It has been incredibly useful to me.

**Comment by NabokD** [comment]
I'll investigate it, but I think changing the shorts filter between change group filters can be even more confusing than the current state.
I hope YouTube backs the channel name under the short in grid view, after that, I can back filtering by group there.
