### ISSUE TITLE
[v15.7.0] "Mark as watched" button isn't working

### ISSUE THREAD

**Issue by pintassilgo** [NabokD/pockettube#74]
In past ~9 days, videos I clicked to "Mark as watched" are still displayed in group view (I use "Unwatched" mode).

I click "mark as watched" in list to hide videos that don't interest me. Videos I actually watch don't show up again when I reload, proving YouTube History is working, only PocketTube "Mark as watched" is failing.

Important: it's needed to reload (or click group again) to check. When I click "mark as watched" the video is removed from the list, but if I reload the group the video returns to the list as unwatched.

I use Firefox.

**Comment by NabokD** [comment]
Thank you for letting me know. It's related to uBlock, try to disable it and after that, it'll work. It is working fine in Chrome with uBlock, but have an issue only with Firefox. 

I've prepared a workaround, however, the Firefox review extension process is slow, so I hope it will be available by to end of next week, I'll inform you.

**Comment by NabokD** [comment]
The new version 15.7.2 is available, try to use it.

**Comment by NabokD** [comment]
Are you sure it is 15.7.2? After clicking mark as watched, don't update the page immediately, just wait around 5 secs and update it after that. Because youtube shows the changes with delay.
