### ISSUE TITLE
Subscription group does not load all video 

### ISSUE THREAD

**Issue by viethung0823** [NabokD/pockettube#75]
as the title, it only load some of the videos when i add [this](url)  channel into a group.

**Comment by NabokD** [comment]
It load only 15 videos, it's expected and restricted by YouTube

**Comment by viethung0823** [comment]
please improve this. I found useful resouce [here](https://stackoverflow.com/questions/18953499/youtube-api-to-fetch-all-videos-on-a-channel). limited 15 video per channel is suck
