### ISSUE TITLE
List of Videos in Subscription Groups include unavailable videos.

### ISSUE THREAD

**Issue by HidyHo** [NabokD/pockettube#76]
I have videos that are "geo-locked" (e.g. many Saturday Night Live channel videos are only available in the USA).

The main subscription page filters out these videos so they are not listed.  However, within PocketTube created subscription groups, these videos are listed only to error out when clicked to view them (as well as shown as "unavailable videos are hidden" when crreating a playlist).

Please filter these videos in the same manner as the main subscription page.

**Comment by NabokD** [comment]
I think there is no way to filter out it because the feed is geo-independent, however, I'll investigate it.

**Comment by HidyHo** [comment]
I just noticed that Subscription Groups in DECK seems to filter out unavailable videos so, perhaps, there is a logic that can be leveraged??

**Comment by NabokD** [comment]
Yes, it has a filter on the channel column on deck, but not on the group.

**Comment by HidyHo** [comment]
I think the logic for Subscription Group has changed.  I no longer see unavailable videos *BUT* it seems like some videos are missing under current logic.  It's good enough for me (to filter and watch the majority of subscribed videos) so I haven't spent too much time trying to figure it out.

**Comment by NabokD** [comment]
No, the logic was not changed, but yesterday YouTube had a bug that had an impact on PocketTube. Currently, it's enabled a fallback strategy to get the video without shorts and live. YouTube already fixed a bug, so it will be disabled with the new version of the extension, and shorts and live will be showing again.

**Comment by HidyHo** [comment]
Today, Subscription Group included a whole bunch of videos including previously watched videos as well as shorts (although I selected Upload only) .  Inconsistent behavior is frustrating :(

**Comment by NabokD** [comment]
It's consistent behavior on the PocketTube side, I don't have the ability to handle bugs on the YouTube side.

**Comment by HidyHo** [comment]
I'm not sure how you can close this as completed.  After this week's many issues (which you pointed out as YT changes), you updated the Chrome extension to 15.7.8.  Now we are back exactly where we started when I logged the issue. 

That is, unavailable videos are listed under Subscription Group.

**Comment by NabokD** [comment]
Because you started a discussion on the issue, which is not relevant to the initial issue. As I said before there is no way to filter out it because the feed is geo-independent.
