### ISSUE TITLE
Error: Subscription Groups show "All videos were watched" - not true

### ISSUE THREAD

**Issue by HidyHo** [NabokD/pockettube#78]
From yesterday, I noticed that Subscription groups were not displaying videos correctly.  When clicking on every group, it shows that "All videos were watched" when there are unwatched videos in the main subscription page. Looing at Chrome Extension page, it shows an Error.

![image](https://github.com/NabokD/pockettube/assets/31374038/e14d4e65-afe3-42d1-9a2a-255c2da0099f)

**Comment by HidyHo** [comment]
I tried to uninstall and reinstall PocketTube and noted an error accessing my Google Drive.  Not sure if it's related to this issue or not.

![image](https://github.com/NabokD/pockettube/assets/31374038/e6837f65-c56c-4e76-891f-76c34890159a)

**Comment by HidyHo** [comment]
It's back working now, although no other changes, since previously reported, were made on my end.  Backup synch with Google Drive still errors the same as reported.

**Comment by KalAvroniev** [comment]
I have the opposite issue. I filter watched but when I go to play it shows all in the playlist. This started after the latest update a day ago

**Comment by NabokD** [comment]
> From yesterday, I noticed that Subscription groups were not displaying videos correctly. When clicking on every group, it shows that "All videos were watched" when there are unwatched videos in the main subscription page. Looing at Chrome Extension page, it shows an Error.
> 
> ![image](https://user-images.githubusercontent.com/31374038/274814288-e14d4e65-afe3-42d1-9a2a-255c2da0099f.png)

It was YouTube issue, which have impact to PocketTube

**Comment by NabokD** [comment]
> I tried to uninstall and reinstall PocketTube and noted an error accessing my Google Drive. Not sure if it's related to this issue or not.
> 
> ![image](https://user-images.githubusercontent.com/31374038/274826189-e6837f65-c56c-4e76-891f-76c34890159a.png)

Try to disable other extensions, typically it's related to conflict with other extensions

**Comment by NabokD** [comment]
> I have the opposite issue. I filter watched but when I go to play it shows all in the playlist. This started after the latest update a day ago. Remove and read did not help

It's not related to the issue, send me a screenshot at hello@pockettube.io and I'll investigate. Also, check YouTube history it should be enabled and maybe some other extensions affect it, try to disable it to test
