### ISSUE TITLE
[Bug] Extension still shows watched videos

### ISSUE THREAD

**Issue by Gethe** [NabokD/pockettube#79]
No matter how many times I watch a video, it still appears in my subscription groups. I recently changed my YouTube handle so I suspect this may be part of it, but I don't know how to fix it.

I've tried removing the extension and reinstalling it, but that hasn't worked. This is on chrome

**Comment by NabokD** [comment]
It's weird, have you watched videos in YouTube history here: https://www.youtube.com/feed/history ?

**Comment by NabokD** [comment]
Also please check the channel tab did you see the watched indicator there?

**Comment by Gethe** [comment]
Yes, they are in my watch history and shows the indicator on the channel page. 

Watch History
<img width="583" alt="image" src="https://github.com/NabokD/pockettube/assets/175624/986f7e23-99f7-4fea-b9f2-a571dc1b0e5d">

Channel
<img width="578" alt="image" src="https://github.com/NabokD/pockettube/assets/175624/71afaa8f-f837-4ad0-9cf5-cb1bc695eb41">

PocketTube group
<img width="588" alt="image" src="https://github.com/NabokD/pockettube/assets/175624/807dc100-356c-4b4a-a496-d5f04fd4f187">

**Comment by NabokD** [comment]
Unfortunately, I can't reproduce the behavior on my feed. Could you give me more information? 
Push button F12(Windows) or Cmd+Opt+J(Mac), switch the console tab, open the feed and send the screenshot to me. Maybe it'll be some errors.

**Comment by Gethe** [comment]
![image](https://github.com/NabokD/pockettube/assets/175624/86346488-79ba-43ee-943a-58ea887b9822)

**Comment by NabokD** [comment]
Thank you! 
Could you please also open the Network tab, filter by https://www.youtube.com/youtubei/v1/browse click on one request, and open preview? It seems YouTube can't handle some requests on your account.

![CleanShot 2023-10-15 at 19 14 55@2x](https://github.com/NabokD/pockettube/assets/10400731/cafb9e37-a947-4a19-94f6-e7ba8092d0c6)

**Comment by Gethe** [comment]
![image](https://github.com/NabokD/pockettube/assets/175624/899c469d-718f-43a3-bc5b-ebfe314d54f2)

**Comment by NabokD** [comment]
Thank you, one more thing could you please open 'Payload' tab near 'Preview'

**Comment by Gethe** [comment]
![image](https://github.com/NabokD/pockettube/assets/175624/1f988793-72e1-49c4-8b51-39c0835c73ea)

**Comment by NabokD** [comment]
Thank you, it seems channel identification is wrong, I'm not sure why. Can you open the channel in the left sidebar under Subscription Groups in the group?
Could you please clarify how you added the channel to the group, is it was on the channel/video page or on the PocketTube dashboard?

**Comment by NabokD** [comment]
and one more test, try to remove the channel from the group and add it again, maybe it helps, however it's really weird

**Comment by Gethe** [comment]
Yeah, I can open the channel from the group list. I added it from PocketTube, the "Set channels for <group>" dialog.

**Comment by NabokD** [comment]
Could you please send me your export file? Click on extension file -> backup -> export, save the file, and send it to hello@pockettube.io I want to check your data, maybe something is wrong on the side.

**Comment by Gethe** [comment]
sent

**Comment by NabokD** [comment]
Thank you, I've got it, I'll investigate it and back to you

**Comment by NabokD** [comment]
I've reproduced the behavior, it depends on the location. It seems YouTube started to provide ID without the prefix UC typically ID is UCZYTClx2T1of7BRZ86-8fow, but in your case it's ZYTClx2T1of7BRZ86-8fow
I've prepared a workaround to fix the issue, the new version is on review, and it takes several days. I'll inform you when it'll be available!

**Comment by Gethe** [comment]
Awesome! thank you!

**Comment by Kyzoku** [comment]
I was just coming here to report what I think may be the same thing.  I have watched videos showing in a subscription group on the deck.

On a side note, have you found a way for videos that are put in the Live or Shorts sections of a channel to show up in the deck without adding them to a subscription group?

**Comment by kachunkachunk** [comment]
Also chiming in with the same experience/problem. Glad you have a workaround in the pipeline!

**Comment by phcs93** [comment]
Hey, I've notice two different bugs but the root cause might be the same:
1. The deck is ignoring my settings to hide "shorts" from my custom columns
2. Also, on custom columns, the duration of each video is not showing anymore and it won't indicate that I've already watched them (with the little red bar on the bottom)

**Comment by NabokD** [comment]
The new version 15.7.8 is available for Chrome, try to use it!

**Comment by Gethe** [comment]
It works! Thank you!

**Comment by aDreamEater** [comment]
Firefox user here. I came to report a similar issue involving the channel ID dropped UC prefix. It's preventing the 'add to queue' button from working from pockettube, instead redirecting to a blank channel page (which displays properly when adding the UC prefix). Hopefully when this fix comes to Firefox it will fix the queue issue as well!

**Comment by NabokD** [comment]
Yes, it is related and the new version will be on Firefox soon, unfortunately, their extension review process is slow on Firefox as usual, I expect it'll be at the end of the week.
