### ISSUE TITLE
Not able to load all subscriptions

### ISSUE THREAD

**Issue by rutgersc** [NabokD/pockettube#8]
Microsoft Edge 
Version 93.0.961.52 (Official build) (64-bit)
PocketTube Version 9.10.3

Google Chrome 
Version 93.0.4577.82 (Official Build) (64-bit)
PocketTube Version 9.10.1

For some reason the extension is only able to see a small part of the subscription list. This is a screenshot from the 'manage channels' section:
![image](https://user-images.githubusercontent.com/7382303/133892492-76be15dc-82e8-4926-9f85-2fa1d6504ff1.png)

Tried with both the microsft store and the chrome store version (by enabling 'Allow extensions from other sources'). When I use the extension on ~~chrome or~~ firefox it's able to load the subscription list just fine.

Update: It seems to relate to me having 2 accounts attached to my email. When I switch between these 2 accounts on firefox it loads the lists correctly. However when I do this on chrome/edge, it sticks to the list of the 1st account, even though the other account is currently active.

![image](https://user-images.githubusercontent.com/7382303/133893324-9bc00bfc-2199-4d23-916e-4dd8b0c1f74b.png)

**Comment by NabokD** [comment]
Hi

Thank you for the message!
I reproduced the issue and included the fix in the next version. It'll be available next week. I'll notify you.

**Comment by rutgersc** [comment]
That's awesome, thanks!

**Comment by NabokD** [comment]
Hi

The new version 9.10.5 is available for Chrome and Edge. Try to use it!

**Comment by rutgersc** [comment]
Works perfectly in edge now. Looking forward to playing around with the extension!
