### ISSUE TITLE
[Feature Request] Retrieving more than 15 videos per channel

### ISSUE THREAD

**Issue by key-one** [NabokD/pockettube#81]
Using Pockettube's play button for a subscription group is quick and responsive. It works well but only shows the last 15 videos from each channel (#75 ). If I want more videos per channel, I need to open my subscription feed (https://www.youtube.com/feed/subscriptions) and filter by subscription group. This is extremely slow because every video in my subscription feed is parsed (with thumbnails rendered) then filtered afterward to only keep channels in the desired group(s).

As an extreme example, if I want to go back to see six months of videos from a group with 3 channels - but I have 500 subscribed channels - Pockettube needs to render and sort a huge number of videos in order to find a small number of matching videos.

Is it possible to either not render thumbnails for videos that don't match; or to cache the subscription feed so it only needs to be enumerated once?

15 videos per channel is fine if the feed is kept up-to-date, but doesn't work for historical browsing.

**Comment by NabokD** [comment]
No, currenly, it's a restricted by YouTube, and no easy way to improve it, so there is no plan to improve it.

**Comment by key-one** [comment]
Thanks for the reply! Not sure if it's feasible for Pockettube, but InoReader (RSS Reader) pulls in every subscribed channels' RSS feed and populates older videos as needed.
