### ISSUE TITLE
Switching user-agent breaks watched list

### ISSUE THREAD

**Issue by bb-nope** [NabokD/pockettube#82]
While using a useragent changer addon for firefox (User-Agent Switcher and Manager)

I encountered that my watched videos were not registering as watched with pockettube. Trying different useragents, or setting a useragent manually also broke this feature. 

Pockettube did not see that I'd watched a single video. 

Pockettube
Version
15.7.10

System:
  Kernel: 6.6.2-arch1-1 arch: x86_64
   Distro: EndeavourOS base: Arch Linux
    
Webbrowser:
  Mozilla firefox for Arch Linux. 
    Version 120.0 (64-bit)

**Comment by NabokD** [comment]
PocketTube doesn't collect watched videos, we're using YouTube history for it. As I see YouTube does not track video when you use different user agents, so I think they're restricting it.
