### ISSUE TITLE
Missing channels in "Subscription groups"

### ISSUE THREAD

**Issue by ssss404** [NabokD/pockettube#87]
I noticed that some channels I'm subscribed to are missing from the channel tab under "Subscription groups". Even when I filter the channels by "without group" they don't show up. Many of the affected channels are inactive (no uploads in 4+ years), don't upload regularly or are active channels I subscribed to a long time ago.

Any idea what's causing this? My account is very old and I'm subbed to around 1.1k channels. The number keeps rising every time I find a channel that wasn't showing up before.

Adding "add to group" buttons to https://www.youtube.com/feed/channels would alleviate the problem.

**Comment by NabokD** [comment]
It's weird. Do you see the channels in the left sidebar? We collect all channels from the sidebar.

**Comment by NabokD** [comment]
You can also add a group on any channel page https://share.cleanshot.com/6nD0bCVH even without subscription to it

**Comment by ssss404** [comment]
There seems to be a YT bug on my end because the sidebar only shows 993 channels.

To give one example: The channel https://www.youtube.com/@subnautica only appeared in the sidebar after I watched a video but the total count of channels in the sidebar didn't increase.

> You can also add a group on any channel page https://share.cleanshot.com/6nD0bCVH even without subscription to it

Yeah I know but I prefer not to.
