### ISSUE TITLE
404 on feeds

### ISSUE THREAD

**Issue by EdinUser** [NabokD/pockettube#9]
Hello!
First, I want to thank you for the extremely helpful extension. It saves a lot of time, and I love it!

Now, about an issue I've found. As of today, 24.09.2021, there are multiple 404 errors on the feeds of the channels. Is this some temporary problem or Youtube changed something?

https://i.imgur.com/mJvoXuD.png

This is on Ubuntu 20.04, Chromium
Version 93.0.4577.82 (Official Build) snap (64-bit)

The issue appears with and without AdBlock Plus.

Greetings!

**Comment by NabokD** [comment]
I think it is a temporary issue on Youtube. In my case, it is working right now.

**Comment by EdinUser** [comment]
Yes, I've checked it now, seems ok. Sorry for the disturbance then! Have a great day!
