### ISSUE TITLE
Extension UX Not Showing

### ISSUE THREAD

**Issue by justinormont** [NabokD/pockettube#93]
Today the extension's UX on YouTube.com stopped rendering. Worked yesterday.

<img width="1264" alt="Screenshot 2024-02-29 at 2 27 57 PM" src="https://github.com/NabokD/pockettube/assets/4080826/60441eee-5b27-4d1e-9b58-1aaeb1270900">

<br/>Nothing obvious in the console:
<img width="1033" alt="Screenshot 2024-02-29 at 2 27 46 PM" src="https://github.com/NabokD/pockettube/assets/4080826/6782b832-56c9-4167-b0af-b273ad1ef8ce">
The PocketTube extension is correctly loaded into the page:
![image](https://github.com/NabokD/pockettube/assets/4080826/7290f9e5-9400-4204-81ad-71e9ec41466b)
Running:
* PocketTube v16.0.2
* Chrome v121.0.6167.85 w/ all cookies blocked on YouTube.com (only kept until the page is closed/reloaded)

Perhaps the DOM / classes / IDs changed and it can't locate which parts to modify? I do end up in random A/B test flights with each page load, but reloading doesn't help this time.

**Comment by justinormont** [comment]
I reloaded ~20 times. The extension UX shows about 1/8th of the time.

Until Google eventually blocked me which is a first with "GOOGLE_ABUSE_EXEMPTION" -- https://www.youtube.com/?google_abuse=GOOGLE_ABUSE_EXEMPTION%3DID%3D6a4c[REDACTED]xjA%3B+path%3D/%3B+domain%3Dgoogle.com%3B+expires%3DFri,+01-Mar-2024+01:52:50+GMT

Since I don't keep YouTube cookies, each reload is a semi-independent set of A/B test flights (e.g. only two columns of videos vs. three, or no videos at all just a "Try searching to get started\nStart watching videos to help us build a feed of videos you'll love." message).

**Comment by NabokD** [comment]
It's weird, maybe it's A/B tests, because I can't reproduce the behavior

**Comment by IngvarListard** [comment]
Obviously, this is because region restriction (ru region)

**Comment by justinormont** [comment]
Mine is set to 'US'. 
![Screenshot 2024-06-19 at 11 45 52 PM](https://github.com/NabokD/pockettube/assets/4080826/0c2c8dbc-c998-48c4-b53a-2961fad3b3da)

That said, I haven't seen this issue in a while, so I'm closing it.
