### ISSUE TITLE
All Videos Not Loading on Video Tab

### ISSUE THREAD

**Issue by PaulErly** [NabokD/pockettube#95]
On multiple YouTube Video pages (https://www.youtube.com/@JoshuaWeissman/videos), several videos won't load initially. Clicking Videos again will mostly fix this problem. Launching Chrome in Incognito Mode also allows all videos to load. 

I uninstalled/reinstalled PocketTube _without_ my settings, and all videos also loaded as expected. However, after re-applying the .json settings, the issue re-emerged. 

I could only find other issues regarding the 15 video limit with Deck, so hopefully this issue has not already been addressed.

**Comment by NabokD** [comment]
Maybe did you enabled a filter on the page?
![CleanShot 2024-03-13 at 21 14 11@2x](https://github.com/NabokD/pockettube/assets/10400731/a678265a-5a1a-4260-9112-572200f0260b)

**Comment by pisarek** [comment]
For me all the videos are being filtered out from the Subsriptions page despite having no filters on. I can actually see it happen in real time.

**Comment by NabokD** [comment]
Send me please screenshot

**Comment by pisarek** [comment]
![image](https://github.com/NabokD/pockettube/assets/9842416/045c0fcd-c39a-4e23-8985-66568f59a8bd)
Then the videos disappear and new ones take their place. For a split second I can see the thumbnails.
Everything works when I disable the extension

**Comment by NabokD** [comment]
but you enabled filters and hide Uploads videos
![CleanShot 2024-03-15 at 23 41 51@2x](https://github.com/NabokD/pockettube/assets/10400731/dcc0e273-4d32-454c-9c39-ac2c3e63803a)

**Comment by pisarek** [comment]
Oh damn, what a brainfart. It works. I haven't ever used those buttons, must have clicked by mistake.
Thanks!

**Comment by PaulErly** [comment]
> Maybe did you enabled a filter on the page? ![CleanShot 2024-03-13 at 21 14 11@2x](https://private-user-images.githubusercontent.com/10400731/312592638-a678265a-5a1a-4260-9112-572200f0260b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1Njg4OTcsIm5iZiI6MTcxMDU2ODU5NywicGF0aCI6Ii8xMDQwMDczMS8zMTI1OTI2MzgtYTY3ODI2NWEtNWExYS00MjYwLTkxMTItNTcyMjAwZjAyNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA1NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYmNiZjIwNGFiNmQzOGFmNjc5ZTEyMmQ1NzFlYmY1NTYzNDhkY2VkYTQ0Y2Y3OGNmMGNiZDVhMGU0NWIxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmAmtMHzRtG837qNPR4vXJQwcHPdfRc3mbyR5pi4mWI)

Interestingly, this was exactly the issue (see 1); no idea how it was enabled. 

However, I find it interesting that you can essentially bypass the filter if you click on videos (see 2) a second time. I didn't think to check for a filter since clicking on "video" a second time made all the videos re-appear.

![image](https://github.com/NabokD/pockettube/assets/73668292/9dbbbca0-4f22-4461-aeef-6d5b7bb1da7f)

**Comment by NabokD** [comment]
Thank you for letting me know, currently, it's expected behavior, maybe I'll find a way how to handle it better in the future!
