### ISSUE TITLE
Auth Error 400 when Enabling Google Drive Sync in Chrome

### ISSUE THREAD

**Issue by astraetech** [NabokD/pockettube#97]
Hi,
First of all, great addon! Been a subscriber for a while. I'm facing a lot of problems right now mostly with syncing across Chrome, Firefox and Android. I will start with just one issue though:

- Pockettube (latest ver) with Chrome (latest version). Trying to enable google drive and i get this response in a pop window:
Sign in with Google
Access blocked: Authorization Error
......gmail.com
If you are a developer of PocketTube: Youtube Subscription Manager, see [error details](https://accounts.google.com/).
Access blocked: Authorization Error Error 400: unsupported_response_type

I tried restarting Chrome and my pc. I tried syncing on Firefox and it has a different problem but it does actually get to the whole enter your account info and 2 factor thing so it's not an account. Searched everywhere and couldn't find this error anywhere so that's why I'm posting this here. 

Btw, is there way for a paid in youtube subscriber to join the patreon?

Thank you

**Comment by NabokD** [comment]
It's weird. Try to disable other extensions, maybe you have a conflict. It can be an extension that changes the URL, or some firewall(some time ago it was with AdGuard), or something like that. 
I've checked, and auth is working now for me.

Yes, you can join patreon.com, next log out on the extension side, and log in using patreon.com on the Patron tab. However, If you already paid using YouTube email, patreon.com does not open to additional benefits, it's the same, just another payment method.

**Comment by astraetech** [comment]
I replicated this on other machines and win versions. I think this happens when your chrome account and youtube accounts are different. No matter what I have tried pockettube google drive sync in chrome throws errors. 

In Firefox, the google drive sync acrtually manages to complete but it never stays connected. Every time you finish the sync the button switches back to Enable and you have to go through the whole process again, but this is a different ticket.
